### ISSUE TITLE
Document the researcher user types

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#122]

**Comment by usanchez** [comment]
What I understood so far is that:
- site admins can do anything anywhere.
- study admins can do anything in their studies and also manage other researchers in those studies.
- researchers can enrol participants and view data, but I don¡'t remember if they can edit surveys. They cannot manage other users.

At this point, I think that it would be good for clarity to have the Researcher class renamed (to Professional maybe?) and the ResearcherRole table would contain the different types of professionals. I'm saying this because maybe we are interested in giving access to other types of professionals that are not researchers (e.g., data managers). If we both the Researcher class and the Researcher ResearcherRole, I think it can be a little bit confusing for newcomers.

Please let me know what do you think. Thanks!

**Comment by biblicabeebli** [comment]
that's pretty much it, though there is a weirdness with site admins downloading data.  issue #116

Can you make a new issue and mark it as a discussion for your Researcher language change?

**Comment by usanchez** [comment]
Done, #128, but I cannot add a label to the issue :(
Wanted to add a "Discussion" label.
