### ISSUE TITLE
Add (optional) names to surveys

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#123]
They won't be used for anything for a while, but the earlier we can do this the better for the future.

**Comment by usanchez** [comment]
Hi Eli, what do you mean by "(optional) names"? Studies already have names, do you want to add to them an alternative name? Adding names to surveys would be very interesting tho. I was planning to this too, let me know if this is what you were thinking about and I can share with you what I've done.

**Comment by biblicabeebli** [comment]
Woops,I don't know why I included studies there.
Optional: there are some problems due to surveys not having names, and one of those problems is that if we introduce names we will still have to wait for researchers to add names to surveys.  The sooner we do it the sooner we can do (small) things that are blocked because of it.

**Comment by usanchez** [comment]
What I have experienced is that is a pain to know which survey is the one I want to access, because the only info I can see of a survey in the survey list is the ID of the survey. If we add a name and other characteristics like, num. of questions in it, last updated and so on, it will greatly increase the use experience of this survey list.

**Comment by biblicabeebli** [comment]
While I'm in there: on the view study page, show the number of questions in a survey....

**Comment by biblicabeebli** [comment]
this was done a while ago....
