### ISSUE TITLE
Language change: "Researcher" class and "Researcher" StudyRelation

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#128]
Right now there is a class that is called _Researcher_, that contains information about the users that can be registered in the web app. However, recently the _StudyRelation_ class was added that states the role that a _Researcher_ user has in a study. The roles that are defined in _StudyRelation_ are include _Researcher_, _StudyAdmin_ and _SiteAdmin_.

I have the feeling that it can be confusing having a class called _Researcher_ and a role that is also called _Researcher_. I think it will be beneficial for sake of clarity, to change the name of the class to something that could generalize the roles that are included in _StudyRelation_.

My proposal was to rename the class: Researcher -> Professional

What do you think?

**Comment by biblicabeebli** [comment]
Valid points, I think Professional isn't the best as I feel it doesn't usually encompass researchers (no offense :b ).  What about 'Collaborator'.

**Comment by biblicabeebli** [comment]
There are also a bunch of instances on the frontend of researcher.

**Comment by usanchez** [comment]
_Collaborator_ sounds better to me, because the _SiteAdmin_ is included in the roles, and it's not a professional. _Collaborator_ sounds better.

Yeah, about the frontend, those are instances that refer to the _Researcher_ class or role, so I didn't specify it but is good to point it out, so we all know the size of this change 😅

**Comment by biblicabeebli** [comment]
Apologies, I thought a coworker had commented, but I see now that it was just an email.

The term "collaborator" is already used by Onella Lab in reference to external researchers, so it is not an option for user-facing details of the site.  On a code level this is a pretty minor linguistic detail with some substantial overhead in doing the refactor.

Beiwe has 2 types of users: participants and "those who run studies," but there is a hierarchy to these researcher-users because there are users who have minimal study-managing privileges, full management privileges, and full admins who can see all studies and make any change.  These are permission levels, not distinct user types, so I'm not convinced a useful relabelling option exists.  "User" seems best because it is generic, but is also unusable because it is generic.

I'm closing this issue as I see no inherent advantage to the proposed change, only a headache and an argument.

I will be creating a new issues for purging all uses of the term "patient id" and "patient_id" from the backend, frontend, and apps.
