### ISSUE TITLE
Don't know best way to download All Raw Unencrypted data

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#130]
I have finished a small study where I have collected all sources of data, but I don't know which is the best procedure to download all raw data to my local computer to test current summary statistics and try new ones. If I run the code of Beiwe Analysis (just to the point of downloading the raw data), the execution gets killed because it takes too long to download the accelerometer data. If I unselect several data types, I can download the data of all participants, but I want to get the rest of the data types too.

Is there a better way to download **all raw data unencrypted** so I can test the summary statistics on my local computer? Would like to go back to issue https://github.com/onnela-lab/beiwe-backend/issues/84 too while I am at it.

**Comment by biblicabeebli** [comment]
Could you post the exact error that occurs causing you to time-out, including any potentially relevant apache print statements if possible?  I've seen mystery timeouts sourced from aws load balancers.

You should make use of the download api via a script.  There is a reference data download script in the `scripts` folder.  You can make a script that iterates participant by participant, or data stream, or time.  Using a script to access the api also allows you to download only files you don't already have / have changed since you downloaded them.  (it generates a json blob of hashes.)

**Comment by usanchez** [comment]
Hi Eli, I'm sorry but I cannot find that "reference data download script in the scripts folder". Is it still in the repo? What's the name of the file?

**Comment by biblicabeebli** [comment]
it is in the `data_acces_api_reference` folder.  I well eventually remember to change the name to `data_access_api_reference`.
