### ISSUE TITLE
Internal Server Error when adding new patients after following the single-server setup

### ISSUE THREAD

**Issue by dengerrrr** [onnela-lab/beiwe-backend#140]
Right now I have already followed all steps of single-server setup and successfully point the AWS address to my domain safari.ece.rice.edu. When I add new patients, the error shows:

**Internal Server Error**
The server encountered an internal error or misconfiguration and was unable to complete your request.

When I check the error log:
`ubuntu:~$ sudo tail /var/log/apache2/error.log
`
`[Wed Jun 03 19:57:04.366085 2020] [wsgi:error] [pid 4881:tid 140025980540672] [remote 128.42.74.125:58975]   File "/home/ubuntu/beiwe-backend/api/participant_administration.py", line 67, in create_new_patient s3_upload(patient_id, "", study_object_id)`
`File "/home/ubuntu/beiwe-backend/libs/s3.py", line 17, in s3_uploadconn.put_object(Body=data, Bucket=S3_BUCKET, Key=key_path, ContentType='string')`
`File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 324, in _api_call
return self._make_api_call(operation_name, kwargs)`
`File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 622, in _make_api_call ### raise error_class(parsed_response, operation_name)`
` ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied No handlers could be found for logger "sentry.errors"`

And I receive an email at ubuntu:
`    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/cronutils/task_runner.py", line 91, in _run_task
    try: function()
  File "/home/ubuntu/beiwe-backend/libs/file_processing.py", line 74, in process_file_chunks
    raise EverythingWentFine(DATA_PROCESSING_NO_ERROR_STRING)
EverythingWentFine: 2HEnBwlawY
processing files for the following users: `

@biblicabeebli How can I solve this?

**Comment by biblicabeebli** [comment]
Hello and thank you for posting!

Okay, first off you are on python 2.  This is one of the reasons the single server option is out of date, we need to finish up current work - which changes backend duties substantially and has therefore been delayed until that work is finished - so that we can update the singler server option AMI.

The first error you are getting is a permission error on the S3 PutObject permissions for the AWS credentials that you provided.  The `Access Denied`issue mentioning a logger is junk, you can ignore it.

The email error you receive (which, for absolutely unfathomable reasons is clears out new line characters on _some_ deployments) is benign.  It is an ancient and terrible pattern that was used for a while, the error class is named `EverythingWentFine` because it occurs when everything is fine.  When we update the AMI the system moves over to a Celery-based processing architecture and is much more robust.

We are getting closing in on the work preceding creating an updated AMI, there will be an announcement on this thread: #99 when that happens, as well as directions on new requirements for the new push notification system.

**Comment by biblicabeebli** [comment]
Did you ever resolve your issues? I would like to close the ticket if you did.

**Comment by dengerrrr** [comment]
Sure, please close it.
