### ISSUE TITLE
Add more aggressive logging cleanup to Elastic Beanstalk instances and generally improve disk space utilization

### ISSUE THREAD

**Issue by jakeczyz** [onnela-lab/beiwe-backend#143]
AWS EB is warning about low space on the instance root filesystem, which is putting the application health into the Warning state.  Is there a recommended way to increase capacity or a cleanup process to run (or cronjob to enable... or logrotate to configure), to resolve space issues on the EB hosts?

**Comment by biblicabeebli** [comment]
Hm.  Well make a big swap file that costs some storage space so its not _that_ difficult to achieve this, but under normal circumstances that shouldn't happen.

Try and ssh onto the server (there is an `eb ssh` command in the awsebcli) and see what is taking up the space.  If its ssh access logs you should close/restrict the port 22 security group.

You can also set up an automatic server replacement in Elastic Beanstalk, weekly should be more than enough to solve any recurrent log issues that may be happening under non-bug scenarios.

**Comment by biblicabeebli** [comment]
Making this issue a feature update, changing title.

**Comment by jakeczyz** [comment]
Thanks for the tips.   The configuration uses the default 8GB disks, and it seems to have a 5GB swap file.  This leaves very little for the OS, app code, and logs.  On my instance /var/log only takes 63 MB.  So, in addition to what this new issue title now states, I'd suggest bumping the default disk size to 12 or 15G or so.

I've enabled Managed Platform updates on the EB environment, and will see what happens after the next maintenance window, when, hopefully, the instance will be swapped without downtime to our study 😬  🤞 .

**Comment by jakeczyz** [comment]
Ok, after my maintenance window instance replacement this evening, my instance transitioned to a good state for about 8 minutes and then returned to Warning due to the root filesystem having low space.  Is it possible to increase the disk size on the instances by at least several GB in order to avoid this, or do you have other advice?

I don't think logging cleanup will help much, sadly.
```
$ df -h /
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1      7.9G  7.1G  709M  92% /

$ du -hs /var/log
792K	/var/log
```

**Comment by usanchez** [comment]
I also had this issue and went to :
Elastic Beanstalk > Environments > environment-name > Configuration

In the "Configuration overview", click on "Edit" in the "Instances" block. Set the "Size" to 12 (or anything higher than your current setting) in "Root volume (boot device)". From this moment on, any new instances will have this disk size.

I don't remember if I had to do anything else but just wanted to point out what I did in the case it helps anyone else.

**Comment by biblicabeebli** [comment]
I guess I must have either become inured to the warning state (I get it pretty frequently and randomly) or somehow disabled the metric as I am operating with very low free disk space.  Apologies for not recognizing that.

Disk space problems have been an issue in the past (totally full storage) on the _data processing servers_, but that's obviously not what is going on.  The only scenario where I've had full disk space on an EB server was when I accidentally left port 22 open.

The swap file was present to handle an old memory leak (zip file generation leaks a dictionary in the DEFLATE algorithm) but that hasn't been used for ages.  A swap is still helpful but I will drop this value down by a gig or 2.

...As with many recent comments I need to do this on development due to the bulk of work staged on it... moving this work to master is... still  imminent.... it is being dogfooded (dogfed?) on our staging server and I've been away on a different project for a while...

I'm marking this issue as closed because it is not a _logging_ issue (which would be a problem for everyone and require some community management), it is a fundamental setup issue that I need to address in a different fashion and, indeed, have already made a commit for it.
