### ISSUE TITLE
Django 1.11 does not play nice with the latest version of django-extensions (3.0.4)

### ISSUE THREAD

**Issue by ravibanks54** [onnela-lab/beiwe-backend#150]
Hello,

Posting this to help anyone with the same issue.

Ran into an issue today that brought down the Beiwe dashboard. A recent release of django-extensions (3.0.4) introduced a commit in which they referenced 'Unique Constraint' which is not available in Django 1.11 (https://github.com/django-extensions/django-extensions/commit/d9866b78aef76b86f69e3cdd45cf3d073b2b3d1c). This results in an Internal Server Error when trying to access the Beiwe dashboard. Looking into the error_log contains the following stack trace:

  File "/opt/python/run/venv/local/lib/python3.6/site-packages/django_extensions/db/fields/__init__.py", line 25, in <module>
    from django.db.models import DateTimeField, CharField, SlugField, Q, UniqueConstraint
ImportError: cannot import name 'UniqueConstraint'

In order to solve this issue, you'll need to update requirements.txt to set django-extension's version to 3.0.3.

**Comment by jakeczyz** [comment]
This issue has also hit me and brought down my environment this weekend.  I'm probably missing a step (I'm new to EB), but after updating the requirements.txt: 
```
    -django-extensions
    +django-extensions==3.0.3
```
and performing `eb deploy`, the deploy itself fails:
```
2020-08-09 14:23:41    ERROR   [Instance: i-00042f5bc00000000] Command failed on instance. Return code: 1 Output: (TRUNCATED)..."/opt/python/run/venv/local/lib/python3.6/site-packages/django_extensions/db/fields/__init__.py", line 25, in <module>
from django.db.models import DateTimeField, CharField, SlugField, Q, UniqueConstraint
ImportError: cannot import name 'UniqueConstraint'.
container_command 04_migrate in .ebextensions/01.config failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
```
Any advice? @biblicabeebli ? 
I'll keep digging, but asking right away as my environment (and study) are down due to this.  Thanks in advance.

**Comment by jakeczyz** [comment]
I think I understand part of what's going on, with respect to EB disregarding the requirements update and failing on deploy.  It seems the `requirements.txt` change must be committed to the git branch that's being used to build the environment (I mistakenly assumed my local file changes are uploaded for the EB deploy, due to the `git pull && eb deploy` workflow for updates...).  

However, I'd rather not have to fork the beiwe repo and point my code to the fork, especially since master is now seemingly broken for all users.  Is there any chance this fix can be deployed to master soon (or another workaround suggested)?

**Comment by zagorsky** [comment]
@ravibanks54 and @jakeczyz it looks like we need to update the Django version- this might take us a few days to do.

As a workaround in the meantime, if you update the Django version in your local `requirements.txt` file, you can stage that file (`git add requirements.txt`) and then run `eb deploy --staged`, which will deploy what's currently staged in Git ([here's a link to the EB manual page](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-deploy.html)).

**Comment by biblicabeebli** [comment]
omg I encountered this while doing final testing of the development branch last week, swapping between master and dev.  dev has new version of django, 2.2, there were side effects that took a while to test and get resolved so I do not recommend blindly upgrading django if anyone is looking at this.  I'm 99% sure that I have a local commit locking to an older version of django extensions on master... 2.9.3??

I'll push a commit, so sorry.

(I just moved, I did this work on my desktop and I didn't want it in the moving truck... it's still at my old place.... щ(ºДºщ) )

**Comment by jakeczyz** [comment]
@zagorsky thanks so much, I just applied it now, and that workaround hit the spot.  My environment is back to running and our study can move forward.   @biblicabeebli good luck wit your move! :)   

It seems like it would be safer for the django-extensions version peg to be in requirements.txt.   Because my EB environment was set to auto-redeploy periodically (due to an issue with root file system being too small https://github.com/onnela-lab/beiwe-backend/issues/143 ).... it picked up the latest django-extensions and broke my env.

**Comment by biblicabeebli** [comment]
pushed fix onto master and production, merged with master and removed fix on development where newer version of django.

**Comment by aware-ravi-bhankharia** [comment]
Thanks for the code fix @biblicabeebli !
