### ISSUE TITLE
Deploying to Data Processors

### ISSUE THREAD

**Issue by aware-ravi-bhankharia** [onnela-lab/beiwe-backend#161]
What's the recommended way to deploy to data processors?

I was making some changes to the data processors (a manager and a worker) and ended up deploying to them by ssh'ing into them, creating deploy keys for Github and running 'git pull' on each processor. However, it occurred to me that this method could definitely be improved :) 

Is there a recommended way to deploy to data processors? Or should I set up CodeDeploy to handle this use-case?

**Comment by biblicabeebli** [comment]
use the launch script's -create-manager and -create-worker commands.  make sure to pull and make sure that the up-to-date version of master is the same as your elastic beanstalk servers.
(the manager is itself a worker.)

Development has additional QOL details but is absurdly delayed due to .... mistakes that we have learned from....

**Comment by aware-ravi-bhankharia** [comment]
Thanks for the reply 😊. Just to clarify, would that spin up new instances? Or simply update the existing instances with new code?

**Comment by biblicabeebli** [comment]
It deploys new servers, reason is simplicity.
The QOL update is a terminate command.
Just AWS-online-console-ec2-terminate your existing manager and worker servers, then run the deploy manager command.

**Comment by aware-ravi-bhankharia** [comment]
Thanks for the clarification!
