### ISSUE TITLE
Ability to disable mobile app's location collection via backend settings?

### ISSUE THREAD

**Issue by jakeczyz** [onnela-lab/beiwe-backend#167]
I don't believe so, based on my perusal of the docs, but, to double check, is there an ability to control what the phone app collects via any backend settings?   Specifically, citing privacy and battery usage, my researchers asked if it's possible to disable location collection. 

If not, this would be compelling backend feature :)

**Comment by zagorsky** [comment]
@jakeczyz yep!  In the beiwe-backend web console, go to the "App Settings"/"Study Device Settings" page for a study (it's one of the links near the bottom of the "View Study" page) and un-check "GPS".

Alternatively, you can check the "Fuzz/anonymize GPS data" box (also on the App Settings page).  That won't affect battery usage, but it will improve privacy.  It generates random latitude & longitude offsets for each participant, and then adds them to all measurements.  So Participant A will have something like 1.30582 degrees added to all their latitude measurements, and 0.93724 degrees subtracted from all their longitude measurements, but you (as the researcher) won't know what those two numbers are, because they never leave the phone.
