### ISSUE TITLE
Downloading study data directly from S3 and decrypting

### ISSUE THREAD

**Issue by roblewis1237** [onnela-lab/beiwe-backend#183]
Hi there, 

We ran a small study on Beiwe v1. Our data is on S3 now and we'd like to bulk download it for all participants. It's not easy to do this through the UI as the amount of data floods the memory of the small EC2 instances we have assigned. Is there some info on how to decrypt the data downloaded directly from S3? 

Thank you!

**Comment by biblicabeebli** [comment]
Hello!  You ask a good question, but the answer is complex.

## Short answer: no.
The server is the only place where the decryption keys exist.  If you saved the original encryption key as prompted at study creation time (or if you grab it from the server) then a script bypassing the server entirely _could_ be written.

## However
Beiwe generally recommends against doing this because it makes credential management more complex.  We assume that Beiwe is used in contexts where rules and laws like HIPA apply, so we always recommend using the credentialling system built into Beiwe rather than rolling your own.

## You can:
1) check out the reference data download script in `data_access_api_reference/download_data.py` and modify it to download all of your data piecemeal.  This code should(?) work with older versions of beiwe-backend, providing you avoid querying for data streams that were introduced in a more recent version.
2) check out https://github.com/harvard-nrg/mano 
This repository is maintained by one of the early Beiwe researchers and is more advanced than the reference script.

#### If you find issues with either, please report them!

I am on both repos and am happy, thrilled even, to help fix bugs.  Note that while forwards-compatibility is a feature we have endeavored to maintain with the data download API there may be issues for which the solution is to update the server.  The python 2 to python 3 in-place upgrade of the beiwe-backend can be tricky.  (Again, happy to help with that too.)


## Direct comments on your post:
Because you say "Beiwe v1" I'm lead to believe that you are running a **quite** old version of the codebase.
Several years ago now, there was a "bug" where compressing the zip file using the python built-in zipfile library would run out of memory.  This is a quality of the only available compression algorithm (DEFLATE) in Python 2.7, so not a "bug" per-se.  _Before the Python 3 transition_ we turned off compression because of exactly the issue you are running into.

Finally, there may be other issues, for which my recommendation is to use the download script or Mano.  For example: depending on an extremely long-running network connection as the single point of failure is not a great idea.

**Comment by roblewis1237** [comment]
Hi biblicabeebli, thanks a lot for you reply. I'll try the script and the mano repo. And yes-- it's quite an old version of Beiwe, we took the latest single machine AMI off of AWS.

**Comment by roblewis1237** [comment]
Also I'll let you know how it goes and will post some notes here.... however, it may be a little while until I get to it

**Comment by biblicabeebli** [comment]
Can I close this issue?
