### ISSUE TITLE
iOS app registration crash

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#187]
We have a bug occurring in the iOS app where the app crashes when registering on old beiwe server instance, or on a server without firebase credentials.

ios issue: https://github.com/onnela-lab/beiwe-ios/issues/17

**Comment by jakeczyz** [comment]
This is affecting my study. Android participants can register, but iOS ones fail with "incorrect patient ID or password" Commenting here for visibility.

**Comment by jakeczyz** [comment]
Hello!  Sorry to have to ask, but my researchers have asked me for an update. Any news on this one? 🤞

**Comment by zagorsky** [comment]
Hey @jakeczyz, we're working on a fix, but the Beiwe2 iOS app is stuck in a loop of appeals with the App Store Review Board.

**Comment by biblicabeebli** [comment]
I hereby choose to declare an important opinion: the app store review process stupid.

**Comment by zagorsky** [comment]
@jakeczyz we finally made it through App Store Review, and this should be fixed in v2.0.1 of the iOS app (currently live for Beiwe2 on the App Store)- you should now be able to register.  However, there's a problem where iOS users on that version (1.7.0, 2.0.0, or 2.0.1) are probably not receiving surveys.  We're working on a fix for that.

**Comment by jakeczyz** [comment]
Thanks for the work on this and for the update!

**Comment by biblicabeebli** [comment]
This was fixed late last week, see details on the other thread.
