### ISSUE TITLE
Fix memory "leak" in `celery_process_file_chunks`

### ISSUE THREAD

**Issue by alvinsiu** [onnela-lab/beiwe-backend#218]
Currently, [`services.celery_data_processing.celery_process_file_chunks`](https://github.com/onnela-lab/beiwe-backend/blob/a84cfc2b96b2161e99608d0e5bbb0c26d53a94e6/services/celery_data_processing.py#L109) exits to solve a memory "leak" issue, but it yields a misleading error message from celery.

This is an untested hypothesis, but it's likely the memory "leak" is due to a [ThreadPool being created](https://github.com/onnela-lab/beiwe-backend/blob/a84cfc2b96b2161e99608d0e5bbb0c26d53a94e6/libs/file_processing/file_processing_core.py#L121) and [doing so within a loop](https://github.com/onnela-lab/beiwe-backend/blob/a84cfc2b96b2161e99608d0e5bbb0c26d53a94e6/services/celery_data_processing.py#L83). ThreadPool allocates memory from the OS for python to use, but once it's done, python doesn't give it back to the OS until it exits (since there is overhead in that process) and instead leaves it around in case it still needs it. So since we're allocating a new ThreadPool in every loop, memory continues to be allocated from the OS until we exit, hence the memory "leak".

Theoretically, if we make the ThreadPool global to the scope it's running in (maybe `services.celery_data_processing.celery_process_file_chunks`? or maybe it might need to be global to celery?), it will let the memory usage be "constant" across iterations of running `do_process_user_file_chunks`, which would allow us to not need to `exit` and just allow celery to clean up memory normally.

**Comment by biblicabeebli** [comment]
All of the testing I have done with threadpools demonstrates to me that, as long as close and terminate are called on the threadpool, python correctly cleans up all memory usage from the threads.  (Note that there are _weirdly substantial_ differences in the run-time statistics between different versions of python, I tested 3.6 and 3.8, its a lot better with 3.8 (cool!), so careful with your python environments.)

Stick this in a file and run it with different options and lines enabled/disabled/changed while watching the memory usage.  Start by enabling and disabling the `close()` and `terminate()` functions.  (Control-c may need to be mashed or held down to stop the program, this is due to python's rules/implementation relating to the thread receiving the terminate signal.)

```
import gc
from multiprocessing.pool import ThreadPool
from threading import Thread
from time import sleep

INNER_ITERATIONS = 1000

def eat_some_memory(*args):
    # instantiate a 2**24 byte obj and then
    # note: this _does_ _not_ get optimized into a static preallocation by python
    x = "x" * 2**24

    # just hang out for a bit so it isn't instantly deallocated
    sleep(0.1)

    # print(len(x))  # if you want proof anything allocated...

    # call the deepest level garbage collection explicitly (Note: this seems to have no effect)
    gc.collect(2)

def do_stuff():
    for i in range(100):
        print(INNER_ITERATIONS)

        # ThreadPool with 10 worker Threads
        pool = ThreadPool(10)

        # run  eat_some_memory  1000 times across those threads.
        # pool.map waits on operations to finish in-order.
        # imap maintains order of outputs, but doesn't wait on anything (it doesn't block)
        # imap_unordered doesn't even preserve order, it just goes.
        # beiwe uses imap_unordered (it is fastest for the compute load inside data processing).

        # pool.map(eat_some_memory, range(1000))
        pool.imap(eat_some_memory, range(1000))
        # pool.imap_unordered(eat_some_memory, range(1000))

        # optional sleep (warning: will tend to confuse)
        # sleep(5)

        # These are the two stop-doing-it functions.
        # Documentation says close stops new things, terminate ~stops the threads.
        pool.close()
        pool.terminate()

        # call the deepest level garbage collection explicitly (Note: this seems to have no effect)
        gc.collect(2)


while True:
    # setup and teardown of namespaces interacts with garbage collection and reference counting,
    # entering a function creates a new namespace and then tears it down.  This mimics the lifecycle
    # of the beiwe data processing code.
    do_stuff()

```

**Comment by biblicabeebli** [comment]
Holy Shit I Fixed It.

I fixed it about 2 months ago, I forgot this issue even existed.

It was something to do with the way we pulled data from the "CSVs" (they are binary strings, we barely treat them as CSVs), a reference to the original file's bytes object remained captured until the generator function finished... except even then for some reason the python garbage collector wouldn't clean some of it up?

During a long-overdue refactor I did some performance tests and determined that there was an optimization I could make. Instead of a generator function we now use the C-level builtin `bytes.splitlines` function, and then `pop(-1)` items off the end of the list. This changes the behavior by returning lines of the csv in reverse order., but we do a `sort` down the line so we don't care.  (This idea was tested _back in the day of print statements_ and I even tried using `collections.deque` to make it work, but there was a data ordering requirement at the time, `deque` was too slow, and my understanding of reference counts was not as good as it is now.)

In the end, especially on large csvs, this was about a 3x improvement, memory usage _without the leak_ is better, and the memory leak is gone.

CLOSING THIS ISSUE FOREVER.
