### ISSUE TITLE
Review and merge all documentation for the iOS, Android, and Backend into a single wiki.

### ISSUE THREAD

**Issue by biblicabeebli** [onnela-lab/beiwe-backend#226]
(And, in my humble opinion, the data science work on Forest too, but that's a larger conversation.)

I am unable to find documentation that I am positive exists, frequently because I remember writing it.  This is irksome and a problem, I can't effectively direct people to the appropriate documentation.  We _do_ have some decent SEO via the longer bug reports on github, this is intentional and effective, but it could be better.

The original researcher's guide, written by the original project manager starting in early development is MIA.

**Comment by biblicabeebli** [comment]
This wiki needs to be merged:
[https://github.com/onnela-lab/beiwe/wiki](https://github.com/onnela-lab/beiwe/wiki)

**Comment by biblicabeebli** [comment]
(and reviewed, I haven't touched it in years.)

**Comment by biblicabeebli** [comment]
The old wiki's bages have been added (with rebuilt links to only reference internal copies of pages) to the backend wiki.  There is no landing page at the moment, waiting on credentials to update the old wiki to link to the backend pages.

**Comment by biblicabeebli** [comment]
And now there is a landing page.
I don't have edit access to the old wiki, not closing this issue until I can update all the pages over there that that wiki is deprecated.

**Comment by biblicabeebli** [comment]
The old wiki has been updated, every page has a notice stating the wiki is out of date, and a link pointing to the equivalent page on the new wiki.  The old wiki will no longer be updated.

Will not be closing issue until I have gone through every documentation page and updated or reviewed content for every page from the old wiki.

**Comment by biblicabeebli** [comment]
@zagorsky @hackdna @kwcarlso 

I've updated and fixed most (all?) internal urls on the newly merged-in wiki content.  I would appreciate some help reviewing and updating it.

I can cover a lot, but there are areas that touch on the analysis side that I'm just not familiar with, and generally it needs some eyeballs.  Also, we should probably update it with respect to the existence of Forest.

I decided it was valuable to preserve the old structure, so there is now a [researcher's landing page](https://github.com/onnela-lab/beiwe-backend/wiki/%5BResearchers%5D-Home) and link to it from the [main landing page](https://github.com/onnela-lab/beiwe-backend/wiki).

Additionally, there is some interaction with the peer review work with respect to [this comment](https://github.com/onnela-lab/beiwe-backend/issues/210#issuecomment-929220831) on the peer review work.

cool final thing:
The wiki is its own git repo, which is super convenient for bulk changes like updating links after a file rename.  The contents of old wiki have been stuck into an `old-wiki` folder for ease of everything; for whatever reason the wiki continues to work flawlessly with this repo structure.
You can clone it with `git clone git@github.com:onnela-lab/beiwe-backend.wiki.git`

**Comment by zagorsky** [comment]
@biblicabeebli thanks for merging the wikis; I think that was a great move.  I thought it would be better to have one consolidated landing page for everyone (instead of one page for researchers, and one for engineers), so I merged all the links into one landing page on [the new wiki](https://github.com/onnela-lab/beiwe-backend/wiki).

I have two requests for you, since I don't have write access to the onnela-lab/wiki repo:
1. Could you please update the "This Wiki Has Moved" link to point at https://github.com/onnela-lab/beiwe-backend/wiki#documentation-for-researchers  ?
2. I think you should delete all content on each page of the old wiki, so nothing is left except the link pointing to the new page.  Otherwise, there's a risk that someone will update the old wiki, and then that info will eventually need to be reconciled with the new wiki, or it will eventually get lost when the old wiki gets deleted.

Thanks.  I don't think anyone else needs to review this; I did a cursory check that the links work and that the content is copied over.

**Comment by biblicabeebli** [comment]
I forgot that we also have _another_ other wiki
http://wiki.beiwe.org/

Will need to work out what to  do with this.

**Comment by biblicabeebli** [comment]
wiki.beiwe.org now redirects to the correct wiki and nobody has complained!
(I am getting admin access to the remaining beiwe repo so that it can be shut down)

**Comment by biblicabeebli** [comment]
why was this one even still open... closing. archiving. this is ancient.
