### ISSUE TITLE
Filtering not working on JSON API endpoint

### ISSUE THREAD

**Issue by clementzach** [onnela-lab/beiwe-backend#282]
I tried filtering the tableau JSON API using the [instructions here](https://github.com/onnela-lab/beiwe-backend/wiki/Tableau-API)

I put this in my terminal:

curl "https://studies.beiwe.org/api/v0/studies/kwqahYjnFDU1cMa0fqaiWIJB/summary-statistics/daily?start_date=2022-02-01&end_date=2022-03-09&participant_ids=z91istgx&fields=date,participant_id,accelerometer_bytes,distance_from_home" -H "X-Access-Key-Id: **real key here**" -H "X-Access-Key-Secret: **real key here**"

It returned a json file with all users, all fields, and all dates, as far as I can tell. 

This is fairly low priority but should probably be fixed to reduce server processing time.

**Comment by biblicabeebli** [comment]
Yeeeeaaah this code path uses the django rest framework, which I haaaaate and is not going to scale because it is suh-looooooow.  I will eventually migrate it to use... maybe `orjson` https://github.com/ijl/orjson ?

Note to future self: I think the fields are being silently discarded because they aren't present in the serializer declaration, because of default behavior... that seems bad? maybe?

Can you check if the value "date" works? I think it will, and I'm also positive that is an oversight.

the current definitive list of filters is....
date
participant_id
study_id
beiwe_accelerometer_bytes
beiwe_ambient_audio_bytes
beiwe_app_log_bytes
beiwe_bluetooth_bytes
beiwe_calls_bytes
beiwe_devicemotion_bytes
beiwe_gps_bytes
beiwe_gyro_bytes
beiwe_identifiers_bytes
beiwe_image_survey_bytes
beiwe_ios_log_bytes
beiwe_magnetometer_bytes
beiwe_power_state_bytes
beiwe_proximity_bytes
beiwe_reachability_bytes
beiwe_survey_answers_bytes
beiwe_survey_timings_bytes
beiwe_texts_bytes
beiwe_audio_recordings_bytes
beiwe_wifi_bytes
jasmine_distance_diameter
jasmine_distance_from_home
jasmine_distance_traveled
jasmine_flight_distance_average
jasmine_flight_distance_stddev
jasmine_flight_duration_average
jasmine_flight_duration_stddev
jasmine_gps_data_missing_duration
jasmine_home_duration
jasmine_gyration_radius
jasmine_significant_location_count
jasmine_significant_location_entropy
jasmine_pause_time
jasmine_obs_duration
jasmine_obs_day
jasmine_obs_night
jasmine_total_flight_time
jasmine_av_pause_duration
jasmine_sd_pause_duration
willow_incoming_text_count
willow_incoming_text_degree
willow_incoming_text_length
willow_outgoing_text_count
willow_outgoing_text_degree
willow_outgoing_text_length
willow_incoming_text_reciprocity
willow_outgoing_text_reciprocity
willow_outgoing_MMS_count
willow_incoming_MMS_count
willow_incoming_call_count
willow_incoming_call_degree
willow_incoming_call_duration
willow_outgoing_call_count
willow_outgoing_call_degree
willow_outgoing_call_duration
willow_missed_call_count
willow_missed_callers

**Comment by clementzach** [comment]
curl "https://studies.beiwe.org/api/v0/studies/kwqahYjnFDU1cMa0fqaiWIJB/summary-statistics/daily?start_date=2022-02-01&end_date=2022-03-09&participant_ids=z91istgx&fields=date" -H "X-Access-Key-Id: [real id]" -H "X-Access-Key-Secret: [real secret]"

returns:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>

**Comment by biblicabeebli** [comment]
Crap, this didn't make it into my tasks.  I just added it.

**Comment by clementzach** [comment]
This is what I got when I tried to filter:


500 Internal Server Error
Sorry, something broke when you tried to access this page. The web application has restarted, and no damage has been done. Please email [kcarlson@hsph.harvard.edu](mailto:kcarlson@hsph.harvard.edu) and describe what happened; if possible, please include the time that this page appeared, so that we can look at the error logs and figure out what broke.

Contact: [onnela.lab@gmail.com](mailto:onnela.lab@gmail.com) © 2014- Harvard University. Built by [Zagaran, Inc.](https://zagaran.com/) and [Onnela Lab](https://www.hsph.harvard.edu/onnela-lab/) Looking for the Android App? [click here](file:///download).


The command I was using was:

curl "https://$server.beiwe.org/api/v0/studies/$study_id/summary-statistics/daily?fields=date,participant_id,accelerometer_bytes" -H "X-Access-Key-Id: $key_id" -H "X-Access-Key-Secret: $key_secret" > data_volume_dict.json

**Comment by biblicabeebli** [comment]
Walp, crap.

**Comment by biblicabeebli** [comment]
Hokay.
That bug was the endpoint having bad error handling code.  >_o
It is fixed, the error with your query is: `accelerometer_bytes is not a valid field`
(its `beiwe_accelerometer_bytes`)

**Comment by martakarass** [comment]
Hi @biblicabeebli I wonder if [the current definitive list of filters](https://github.com/onnela-lab/beiwe-backend/issues/282#issuecomment-1065820530) should be pasted to the [Tableau API wiki on onnela-lab/beiwe-backend](https://github.com/onnela-lab/beiwe-backend/wiki/Tableau-API)?

**Comment by clementzach** [comment]
@martakarass I added it at the bottom of the wiki page. Does that seem good to you guys or should we make a new page with that information?

**Comment by biblicabeebli** [comment]
> Hi @biblicabeebli @clementzach I wonder if [the current definitive list of filters](https://github.com/onnela-lab/beiwe-backend/issues/282#issuecomment-1065820530) should be pasted to the [Tableau API wiki on onnela-lab/beiwe-backend](https://github.com/onnela-lab/beiwe-backend/wiki/Tableau-API)?

Uuumm, probably, but that may be out of date.  I'll have to review and paste a list of fields.

**Comment by biblicabeebli** [comment]
I have updated the documentation, closing this issue.
