### ISSUE TITLE
Data batching/chunking not running automatically on AMI deployment

### ISSUE THREAD

**Issue by zagorsky** [onnela-lab/beiwe-backend#29]
Error report from Zhe: when starting an AMI, data batching/chunking doesn't automatically start running.  Could be caused by:
> a typo in the cron script. The script is `beiwe-backend/services/ami_cron_target.py`. In the TASKS parameter, the task listed, `process_file_chunks()`, should be written without the parentheses? I think it should be "FIVE_MINUTES: [process_file_chunks]"?

Also:
> running "process_file_chunks()" directly, I ran into an error where the database is already locked?
        error text: `ProcessingOverlapError("Data processing overlapped with a previous data indexing run.")`

**Comment by zagorsky** [comment]
The first half of this issue (that data batching doesn't automatically start running) should be fixed in 0368eee.  The second half of this issue (that file processing is locked when the AMI first boots up) is still pending a fix.

**Comment by zagorsky** [comment]
We think this issue happened because `process_file_chunks()` was run manually and errored, failing to release the `FileProcessLock`.

The root cause of the  `process_file_chunks()` errored should be fixed in #30.

Also, 34fc5a5 should make `process_file_chunks()` relinquish the `FileProcessLock` if it errors.

**Comment by writezhe** [comment]
Hi, sorry to bring this up the second half of this again. This may be limited to just AMI v0.2, and may already be fixed in commit 2f48843d0ae500e4ce8611cbb226ce5e6bad4e77 on , but the AMI only included commits up to April 17, 2018.

The automatic data chunking worked for perhaps a few hours, and then it stopped. 
issue A) Every 5 minutes, in the `/var/log/syslog` file, cron attempts to run `file_processing.py`, and then kills the python process due to memory concerns. One of the log lines consistently reads: `Out of memory: Kill process #### (python) score 939 or sacrifice child`.

issue B) Seemingly unrelated to the out of memory issue, the chunking would not run automatically without me adjusting the `FileProcessLock` lines in `file_processing.py`. I tried this several times, where I would revert to the original code to see if it works, and consistently the chunking wouldn't occur until I inserted a hotfix line to manually `FileProcessLock.unlock()`.
(Even when the automatic chunking is working though, the `/var/log/syslog` would still report memory issues, and kill the process; sometimes processing some of the files before killing the process. If there are too many files to chunk at once, this may make sense, since the server has a small memory size; however, I continued to notice it even after the chunking had been running for a while and was only chunking recent GPS data from the last hour [no accelerometer].)

**Comment by sesterki** [comment]
Hi, 
Issue A was an issue with one of the external libraries used by the beiwe backend and is fixed in commit 5283daa9561f0b587e5e5884b1b10bababc72d9d. You can resolve this issue by running pip -r Requirements.txt

Issue B is likely because the out of memory error immediately kills the process, and FileProcessingLock.unlock() never got executed.

**Comment by zagorsky** [comment]
@writezhe, we just added some instructions on how to update a single-server AMI deployment: https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-instructions#updating-your-single-server-deployment.  I hope that fixes the issue- please let us know!

**Comment by biblicabeebli** [comment]
python 2 is no longer supported, data processing is about to remove underlying architecture involved in this report. closing.
