### ISSUE TITLE
Accessing "PROBLEM_UPLOADS"

### ISSUE THREAD

**Issue by amgeronimo** [onnela-lab/beiwe-backend#295]
I've been having inconsistent uploads of audio surveys for iOS devices on my Beiwe study.  I found that at least some if not most/all of these missing files are being stored in a purgatory "PROBLEM_UPLOADS" folder in my S3 bucket.  Are these problem uploads recoverable, or are the files corrupted?  If the former, is there functionality in the codebase for me to attempt their download?  Thanks very much Beiwe team!

**Comment by biblicabeebli** [comment]
(General update)

I believe the underlying issue is with audio files is due to the encryption code failing; audio files use a separate code path from the rest of the codebase to handle encryption.

Much of the recent work on the ios app was to clean up the *abysmal* encryption code, the current state of which can be found here: https://github.com/onnela-lab/beiwe-ios/blob/eli-fixes/Beiwe/Managers/DataStorageManager.swift  Specifically audio encryption uses the EncryptedStorage class.

Part of this work included *fixing the thing to report errors in encryption instead of silently failing*. The updated code has been out for a couple weeks now, and I have new error reports! So I can begin really debugging this.

**Comment by biblicabeebli** [comment]
Recoverable uploads:
It might be possible, it might not.

The problem uploads folder is present to capture all undecryptable files.  There are/were several major bugs in iOS encryption, most of which are of the form of lacking the RSA-encoded AES decryption key entirely.  However, that's with non-audio files, which, since they use a separate code path, could be totally different.  I don't have many corrupted audio files to work with on my deployments to work with, so let's take a look at those. (I'll be in touch with you out-of-band about looking directly.)

**Comment by biblicabeebli** [comment]
The underlying cause of this issue (ios audio file corruption) was resolved some time ago.
