### ISSUE TITLE
iphone->android TypeError 

### ISSUE THREAD

**Issue by amgeronimo** [onnela-lab/beiwe-backend#304]
We recently transitioned a subject from an iPhone to an Android device.  We kept the same user ID, unregistered the iphone in the portal, and registered the android.  Since then I have been getting sentry errors in celery.  At least one is related to attempting to find an ios log file (a holdover from when the iphone was registered?).

I believe re-registering this user under a fresh ID may fix the problem.  Ive unregistered the user and ended data collection.  I have not got confirmation that they have uninstalled on their end.  Errors are still accumulating.

Thanks,
Andrew

https://sentry.io/share/issue/a41c0d50071e41be80cf6024db6a1b16/

Along with this breadcrumb:
celery.redirected FAILED TO UPDATE: study_id:xxxxx, patient_id:xxxxxx, data_stream:ios_log, time_bin:463379, header:b'timestamp,UTC time,launchId,memory,battery,event,msg,d1,d2,d3,d4'

**Comment by biblicabeebli** [comment]
If anyone experiences this issue you currently need to ssh and manually identify the file causing this problem. (Look for overlapping hourly time ranges, the underlying cause is that data formatting is not identical on ios and android in some cases, so the logic breaks when there is a single hour that contains data from both ios and android).

This is a low-priority issue that I will attempt to get around to fixing, but the scenario is quite rare and the data impact minimal.  Only some data streams are affected.
