### ISSUE TITLE
A few issues with the wiki's deploy page

### ISSUE THREAD

**Issue by erinn** [onnela-lab/beiwe-backend#60]
Under https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-instructions#configuring-ssl

- (Step 1) Expanding the section on how to install the ssl certificates/where would be useful, you seem to be designing for the ELB to terminate SSL, which is fine, it's just a bit unclear if you are not aware of how autoscaling works and how everything comes together.

- (Step 2) This appears to be erroneous, the rewrite goes into place by default, which is probably a good thing, but leads towards the server sending a response to use https and the ELB not being configured for HTTPS by default. I'd suggest rewriting to say the a SSL/TLS certificate is required for the thing to function. (Or I did something wrong with my deploy, but it was pretty much bog default).

This section: https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-instructions#set-up-the-aws-elastic-beanstalk-command-line-interface-eb-cli

- You may want to mention that if a ~/.aws/credentials file is in place it will use it by default, and you will not be prompted for credentials, I allude to this in #58 

- (Step 2) change reference: 64bit Amazon Linux 2018.03 v2.8.2 running Python 2.7

Finally, the default user and password are mentioned in the monolithic deploy, but are not in the cluster deploy, it might be a good idea to have the doc explain a couple of next steps at a minimum after the thing is deployed. Log in here, using these credentials, etc. perhaps as a separate doc linked from the deploy doc.

Thanks for putting this together.

**Comment by biblicabeebli** [comment]
(woops, missed this when it came in)

Step 1: We have also looked into how to set up SSL termination at the server instead of the ELB, I do not recall the details but I think it requires a VPC-level setting, and it might go hand-is-hand with a custom ssl cert.  What's the detail that you think this section is missing? custom ssl directions?

Step 2: Ah, yes this needs to be updated.  Looks like I updated that file to address a different issue and left it uncommented.  I actually want to remove this file from the repo entirely (because it needs to be edited and updated on a deploy-by-deploy basis) and have an example file instead.

----

I agree with your assessment in #58, I'll try and find some time to do this.

64bit Amazon Linux 2018.03 v2.8.2 running Python 2.7 - You are correct. and we may need to check whether AWS Linux 2 is going to replace the existing platforms. (and also the codebase needs to be converted to Python 3 now that python 2 is end-of-life'd in 2020, which is not a trivial thing for this project. It is going to cause mayhem.)

**Comment by biblicabeebli** [comment]
I've tried to update the docs for the first two issues, and I've updated the reference AWS version from the second step 2, and I'm making a note to determine if there is a good way to remove that file from the repo without causing too much chaos.

And thank you for the feedback!
