### ISSUE TITLE
Current master does not chunk data

### ISSUE THREAD

**Issue by erinn** [onnela-lab/beiwe-backend#70]
The current master branch when deployed to AWS in the highly scalable setup does not automatically 'chunk' the data, the cron file will not work on the manager or the processing server because the boto library is not installed, further the crony.py will not work because it imports hourly, daily etc from pipeline import index and index has all of those commented out: https://github.com/onnela-lab/beiwe-backend/blob/master/pipeline/index.py#L121 . So in order to get the cron job that is installed by default working, boto must be installed and the code in pipeline/index.py has to be uncommented. Once that is done the data will be chunked.

This makes doing a working deploy at this point... difficult. I can certainly fix the issue by uncommenting the code etc. I am just not sure what direction you folks are going with the chunking and that may not be the correct approach.

**Comment by biblicabeebli** [comment]
For now use the production branch.  sorry for the inconvenience, active
development probably caused this, will look into this ASAP.

There might be python 3 issues/conflicts.
Feel free to get in touch directly if you would like help resolving the
currently deployed issues.  Pipeline is functional but still unfinished so
there may be some remaining hoops to deal with before it is satisfactorily
configured and functional.  Will update you out of band when that
particular development resumes.

**Comment by biblicabeebli** [comment]
Oh lol.
Okay, this is because I cleaned up the requirements file, I just fixed this
on the python 3 branch, forgot that some of the requirements file updates
had made it to master.

This issue is a bug, we failed to replace a last usage of the old
non-boto3-library in the data processing code.  This means that a
particular error (with extremely low likelihood of occurring, it can only
happen when s3 is out of sync with itself, which happened when s3 went down
a couple years ago) case was not handled.

I've patched this, replaced the error type with a new
"OldBotoImportThatNeedsFixingError" error type that will never be
reachable.  When/if the appropriate boto3 exception happens I will update
the error type accordingly.

**Comment by biblicabeebli** [comment]
Apologies for the inconvenience, the side effect of some of the pre-python 3 updates were not tested for deployment purposes, only to check that it didn't break existing deployments.  Full deployment testing will occur with the python 3 data processing update, which is in-progress waiting for me to find the time to.... do it.

There will be directions for updating deployments to python 3.  It has several steps (deploy a downtime mode that is compatible between the two) but shouldn't be all that hard; it will require deleting existing manager / worker servers, but will probably also have an option to make the manager server a worker+manager server to save on costs.
