### ISSUE TITLE
Run and Test beiwe-backend on local machine

### ISSUE THREAD

**Issue by adityakamble49** [onnela-lab/beiwe-backend#76]
I have gone through [Deployment Instructions](https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-instructions) and other [Wikis](https://github.com/onnela-lab/beiwe-backend/wiki) provided under this repository, It has detailed instruction about deploying this server backend to AWS but is there any way I can test this server locally and connect Android application to localhost server.

After running any manage.py command I am getting following message to setup AWS configuration

```
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    import config
  File "C:\Users\Aditya\Documents\workspace\ta-big-data-design\beiwe-backend\config\__init__.py", line 96, in <module>
    raise BadServerConfigurationError("\n" + "\n".join(sorted(errors)))
config.BadServerConfigurationError:
BEIWE_SERVER_AWS_ACCESS_KEY_ID was not provided with a value.
BEIWE_SERVER_AWS_SECRET_ACCESS_KEY was not provided with a value.
DOMAIN_NAME was not provided with a value.
FLASK_SECRET_KEY was not provided with a value.
S3_BUCKET was not provided with a value.
SENTRY_ANDROID_DSN was not provided with a value.
SENTRY_DATA_PROCESSING_DSN was not provided with a value.
SENTRY_ELASTIC_BEANSTALK_DSN was not provided with a value.
SENTRY_JAVASCRIPT_DSN was not provided with a value.
SYSADMIN_EMAILS was not provided with a value.
```

Is there any way I can update code or configuration to test the beiwe-backend code on local machine

**Comment by biblicabeebli** [comment]
Good question, but the short answer is no because the app forcibly requires
an ssl certificate to upload data.  I acknowledge that this is restrictive,
but this app is designed to contain and transmit personally identifiable
records + exact location data so we have this as a hard-coded requirement
for ... legal reasons.
(There *probably* would be a way to run apache/whatever locally and attach
to that? with a certificate? somehow?)

You can run the server locally without an ssl cert, you just need to
populate those variables (the project is configured to use a sqlite
database for purely local debugging, or you can connect to a remote
database that is your production database).

There is the AMI (amazon machine image, near-zero-setup as long as you have
an AWS account) - but it is seriously out of date and needs to be rebuilt
for Python 3....

You can manually install and run Beiwe on an Apache server and set up
Let'sEncrypt.  (If you do this.... please take notes of what you did and
post them here?  I just don't have resources to run a manual server setup.)

The *real* answer is actually to do a custom build of the android app
(beiwe-android), replacing the import line that reads ```import
javax.net.ssl.HttpsURLConnection``` in the PostRequest.java file + all
usages of ```HttpsURLConnection``` with ```HttpURLConnection```.  (I'm not
entirely sure what the non-https import is, I thought it was
```javax.net.HttpURLConnection``` but my ide is yelling at me.)

**Comment by biblicabeebli** [comment]
(Hope one of those hit your question. :b )

**Comment by adityakamble49** [comment]
Thanks @biblicabeebli for detailed explanation. 
I think its better to go for AWS Deployment using 2nd method _[Robust, scalable setup (configuring a server cluster)](https://github.com/onnela-lab/beiwe-backend/wiki/Deployment-instructions#robust-scalable-setup-configuring-a-server-cluster)_ with minimum instance for testing
