### ISSUE TITLE
'eb init' fails with 'ERROR: NotFoundError - Platform "64bit Amazon Linux 2018.03 v2.7.0 running Python 2.7" does not appear to be valid'

### ISSUE THREAD

**Issue by jakehemmerle** [onnela-lab/beiwe-backend#80]
Turns out 'eb init --debug' logs the AWS API response, which lists the possible values of 'default_platform' for .elasticbeanstalk/config.yml file in the 'SolutionStacks' JSON key. Searching through it, I found an acceptable version using Python 2 (being v2.9.4).

Perhaps this would be more useful to add to the wiki under step 2 of 'Set up the AWS Elastic Beanstalk Command-Line Interface'? Correct me if I'm wrong, but it does not appear that I can change the wiki myself.

**Comment by jakehemmerle** [comment]
I also see this discussed in #60

**Comment by usanchez** [comment]
The platform has been updated to Python3 recently, so if there is no specific reason for you to use Python2, I would opt to upgrade to python3.

However, I think that the deployment instructions do not take into consideration that the main branch is using Python3 and not Python2. So, my personal suggestion (I'm not from the team that is developing the platform) would be to upgrade to Python3, and for the team to update the instructions so it set ups a Python3 platform instead of a Python2 platform.

It's tricky because Python3 was recently developed so you got the platform installed in the "transition from Python2 to Python3" phase of the project and we should expect a lot of changes coming to the different guides to adjust to this change.

**Comment by jakehemmerle** [comment]
I see, so build it straight to Python 3 instead of going to 2 and then upgrading?

**Comment by biblicabeebli** [comment]
Unai's got this pretty straight. (Apologies for my slow response, holidays plus a slew of new and exciting failure modes on the high-load cluster I manage have kept me busy.)

My guess here is that AWS has deprecated the Python 2 platform totally, can't confirm.

Unfortunately this file should not be in the repository at all, its presence is a mistake, but I don't know how to remove a file without deleting it for everyone, everywhere.  Would love a proposal on a clean way to do that.

This line in the config file - as far as I can tell - is ignored except on first run by the EB command line tool.

I ... will have to push a change on master and production to update this line to python 3 because it is apparently blocking new deploys.  I guess at the very least I can put a comment in there stating the file will be removed from the codebase and admins should make backup config files.

**Comment by biblicabeebli** [comment]
I have pushed a fix for this, the default file now contains a warning that the file could be removed from the repo at any time and that administrators should make backups.
