### ISSUE TITLE
Is pycrypto obsolete?

### ISSUE THREAD

**Issue by usanchez** [onnela-lab/beiwe-backend#83]
(formerly "is pycrypto obselete?")

Regarding issue [`Data Pipeline won't run: Missing Schema invalid URL`](https://github.com/onnela-lab/Beiwe-Analysis/issues/5) I'm trying to install all required packages with `Python36`. However, it seems that `pycripto` is not compatible with `Python36`, and looking over the internet it seems that it may be obsolete? (for example [GitHub issue](https://github.com/dlitz/pycrypto/issues/218)) and that `pycryptodome` should be used instead.

I see that in the [`requirements.txt`](https://github.com/onnela-lab/beiwe-backend/blob/master/requirements.txt) file, the latest version of `pycripto` is specified and `pycryptodome` is commented out just above `pycripto`, so I guess that it was planned to be added in the near future or it was considered but rejected because "reasons"?

Thank you very much!

**Comment by biblicabeebli** [comment]
I could not get Pycryptodome to work correctly during the python 3 port.  I intend to file a bug report when I have the chance to re-investigate it, my understanding is that there are concerns about randomness of random seeds in pycrypto, nothing more.

Pycryptodome claims to have highly accelerated encryption math, which would be really nice.

**Comment by usanchez** [comment]
I've been playing with `pycrypto` and `pycryptodome` recently. I've been testing this piece of code:

```python3
from libs.s3 import s3_retrieve
from database.study_models import Study
from database.user_models import Participant

p = Participant.objects.get(pk=124)

s = Study.objects.get(pk=p.study_id)

c_pub_k = s3_retrieve("keys/" + p.patient_id + "_public", s.object_id)
c_pri_k = s3_retrieve("keys/" + p.patient_id + "_private", s.object_id)

# Pycrypto
from Crypto.PublicKey import RSA
c_pub_k_rsa_key_import = RSA.importKey(c_pub_k)
c_pri_k_rsa_key_import = RSA.importKey(c_pri_k)

# Pycryptodome
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP

c_pub_k_rsa_key_import_dome = RSA.import_key(c_pub_k)
c_pri_k_rsa_key_import_dome = RSA.import_key(c_pri_k)
c_pub_k_rsa_key_import_cipher_dome = PKCS1_OAEP.new(c_pub_k_rsa_key_import_dome)
c_pri_k_rsa_key_import_cipher_dome = PKCS1_OAEP.new(c_pri_k_rsa_key_import_dome)
```

I got this code from the `get_RSA_cipher` functionin `encryption.py`:

```python3
def get_RSA_cipher(key: bytes) -> RSA._RSAobj:
     return RSA.importKey(key)

# `pycryptodome`: the following appears to be correct, but `pycryptodome` raises a decryption error.
# RSA_key = RSA.importKey(key)
# cipher = PKCS1_OAEP.new(RSA_key)
# return cipher
```

If I run the `pycrypto` code, I get these values for `c_pub_k_rsa_key_import` and `c_pri_k_rsa_key_import`:

- `c_pub_k_rsa_key_import`:

> <_RSAobj @0x7fe05555eac8 n(2048),e>

- `c_pri_k_rsa_key_import `:

> <_RSAobj @0x7fe05556ac88 n(2048),e,d,p,q,u,private>

Fo the `pycryptodome` code, I get these values for `c_pub_k_rsa_key_import_cipher_dome` and `c_pri_k_rsa_key_import_cipher_dome`:

- `c_pub_k_rsa_key_import_cipher_dome`: 

> <Crypto.Cipher.PKCS1_OAEP.PKCS1OAEP_Cipher at 0x7f7d9b1ebc50>

- `c_pri_k_rsa_key_import_cipher_dome`: 
> <Crypto.Cipher.PKCS1_OAEP.PKCS1OAEP_Cipher at 0x7f7d9b1dd6a0>

I see that these are totally different objects, but I just wanted to test the code. Where exactly are you getting the decryption error? I would like to try to reproduce it to try to help you with this issue.

Thank you very much!

**Comment by biblicabeebli** [comment]
Yes, there is also a fundamental syntax/object-pattern change required, it is not a drop-in replacement.

The issue I was running into was that the code I wrote that seemed correct to me in pycryptodome's new structure said that my data could not be decrypted.  I set it aside because this library upgrade, while nice, is not critically necessary for the running of beiwe.

Crud, I can't find my code snippet that threw an error.... 

Let me know what you find out in your debugging, I'll try and check on an older system install whether I have that snippet.  Uhg. 

(would love to merge in a fix or assist with debugging/posting a bug report to the pycryptodome repo.)

**Comment by usanchez** [comment]
I'm sure that is because of my limited understanding, but I have a feeling that this issue is a blocking issue (don't know if critical) because pycrypto is not compatible with python3 (again, maybe I have installed it incorrectly, I don't know).

I'll try to work on it and keep this post updated.

Thank you very much Eli!

**Comment by biblicabeebli** [comment]
pycrypto is python 3 compatible, I may have said in another issue that is wasn't but I was wrong.

**Comment by biblicabeebli** [comment]
Pycrypto has been replaced with pycryptodome for all AES related encryption.  It is at least 3 times faster for both encryption and decryption due to the added hardware acceleration support in the newer library.  Beiwe uses this heavily and it possibly directly linearly increases the number of users that a given server can support.  This work is on development.

I had an issue where the RSA encryption/decryption was no longer syntax compatible and it was not obvious how to convert it to pycryptodome.  As this isn't a performance critical operation (it only happens once per file upload, the call to get the key file is slower) I'm not intending to upgrade it.

Marking issue as done because testing is concluded on this work.
